# Generated by Django 3.1.7 on 2021-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
